ENV: 'DEV'
DEV_CHANNEL: Chill Lounge
PRODUCTION_CHANNEL: Chill Lounge
PANIC_CHANNEL: Chill Lounge

username: Daemobot
address: 'mumble-eu.koalabeast.com'

data_folder: 'data'
help_file: 'data/help.html'

default_server: test

mods:
  - Daemien
  - Carbon
  - Damien
  - Ruud
  - hf
  - ' Comacomacomakip'

bans:
  -

ban_channel: SHAME
