group_created: "A group has been created in <a href=\"%{group_link}\">%{text}</a>. It will delete itself briefly if no one joins."

unknown_server: "Unknown server was provided: %{server}."

invalid_command: "Invalid command."

insuficient_arguments: "Invalid number of arguments were provided."

no_permissions: "You don't have permissions to run that."

user_not_found: "%{user} not found."

user_found: "Found %{user} on <a href=\"%{url}\">%{channel}</a>."

greet_set: "Added greeting for %{user}."

no_greet: "No custom greeting defined for %{user}."

no_help_file: "No help file was found. Blame the devs!"

no_stream: "No streams available at the moment."

stream_set: "Stream was set!"

invalid_stream: "Invalid stream."

stream_reset: "Stream was reset!"

greetings:
  - "Ohai!"
  - "Well, hello there!"
  - "lolno"
